"""empty message

Revision ID: 329254df02b4
Revises: 729adf332b4c
Create Date: 2020-07-21 12:37:47.495132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329254df02b4'
down_revision = '729adf332b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
